# fly.toml app configuration file generated for tilt-badgr-server-dark-breeze-6009 on 2025-06-27T15:12:21+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tilt-badgr-server-dark-breeze-6009'
primary_region = 'lhr'

[experimental]
  auto_rollback = true

[build]
  dockerfile = '.docker/Dockerfile.api'

[deploy]
  release_command = 'python manage.py migrate'

[env]
  DJANGO_SETTINGS_MODULE = 'badgr.settings.production'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
