FROM python:3.7-slim

RUN mkdir /badgr_server
WORKDIR /badgr_server

COPY requirements.txt              /badgr_server
COPY manage.py                     /badgr_server
COPY .docker/etc/uwsgi.ini         /badgr_server
COPY .docker/etc/wsgi.py           /badgr_server
COPY apps                          /badgr_server/apps
COPY .docker/etc/settings_local.py /badgr_server/apps/mainsite/settings_local.py

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y \
    libpq-dev \
    python3-dev \
    default-libmysqlclient-dev \
    build-essential \
    xmlsec1 \
    libjpeg-dev \
    zlib1g-dev \
    libpng-dev \
    libcairo2-dev \
    libssl-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install -r requirements.txt
RUN pip install uwsgi


